consult.el
I'd find it useful for the yank commands to some special category so I can configure embark to display them vertically instead of in a grid view. But even without that selfish motivation, it's probably a good idea to have them report some category.
I choose the name `kill-ring` for the category, but maybe you have a better suggestion.
=> Have the consult-yank* commands report the category 'kill-ring

README.md, consult.el
This is a first draft regarding adopting the history command by @oantolin https://github.com/oantolin/completing-history.
I replace the command `consult-minibuffer-history` by a more general variant.
For now it is a bit simpler than the original and I would like to discuss a few things:
* ~Why not use minibuffer-history directly, why is there minibuffer-history-variable etc?~
**EDIT**: I understand this now. It makes sense to have the indirection to allow overwriting the history from outside.
* ~In contrast to the original, I do not enable-recursive-minibuffers for now. I have them generally on but I am not sure if I should instead turn them on always for consult--read. I think I have to play around with them being turned off in order to understand if it makes sense. I am so accustomed to …
=> replace consult-minibuffer-history by consult-history

README.md, consult-flycheck.el, consult-selectrum.el, consult.el
The goal is to separate completion-system-specific logic completely from the rest. Selectrum-specific logic has been moved to consult-selectrum.el. Furthermore flycheck-specific has been moved to consult-flycheck.el.
Note, that there is still 'consult-buffer` which contains selectrum-specific code. This is not addressed here and ~will be adressed later, see discussion in #10.~ has been addressed in #55.
I think I am happy with now - the code is indeed cleaner since no completion-system specifics are mixed with the rest of the code. There is also no regression in behavior. The only disadvantage is that some users have to install three packages now. In contrast, for users who don't use flycheck/selectrum this is an advantage.
=> Split package, such that consult.el depends only on Emacs core components

README.md, consult-flycheck.el, consult-selectrum.el, consult.el
I implemented the low-tech consult-buffer solution. I prefix everything with "b#" etc. The prefix is hidden with the display property which is nice. However in order to narrow one has to press "b # SPC" and this is worse than the old behavior. Furthermore there is no support for showing invisible buffers anymore. The consult--buffer-selectrum implementation supported pressing SPC and then only the invisible buffers where shown.
~I don't like it.~ Now I do!
See #10.
Ping @clemera @oantolin 
**UPDATE**: I prefix everything with "b [zero-width-space]". Then I modify the keymap such that if pressing space after a prefix character like "b", it inserts "[zero-width-space] SPC". This works nicely, allows widening by deleting the prefix characters again etc. I am happy with the solution. It is …
=> General support for narrowing prefixes (used by consult-buffer and consult-flycheck as of now) 

consult-selectrum.el, consult.el
This simplifies the way the keymap gets setup which allows removing the `consult--minibuffer-map-hook` and the menu filter for `SPC` also makes sure the `C-h k` works as expected and if `SPC` is bound to something else than `self-insert-command` it will continue to do so.
=> Use different approach to install narrow setup

consult.el
When completing files with consult-completion-in-region, the point in
the minibuffer gets placed initially at the beginning of the last path
component. With this change it starts at the end of minibuffer
contents, as for other types of completion.
=> Fix issue #48

consult.el
Some defcustoms are defaulting to `nil` without this being an allowed value.  So add `nil` as a type choice.
Fixes #110.
=> Allow some defcustoms to have nil as a valid value

consult.el
`with-suspended-isearch` actually starts a new Isearch if applicable.
=> consult-isearch: remove unnecessary line

CHANGELOG.org, consult.el
@oantolin I just saw your commit, https://github.com/oantolin/emacs-config/commit/30443cc11078a2d5e8d3753efe95629461413b92. Do you think it makes sense to make this truncation behavior the default? I think I only truncated the register string because the original function does it. In our case showing the full string makes more sense and is more consistent with the consult-register ui, which does not truncate.
=> consult-register-format: Do not truncate strings

consult.el
consult-register-load was using the opposite convention than
insert-register. Without a prefix argument, consult-register-load
leaves point before the inserted text, and with a prefix argument,
after; insert-register does the opposite. This simple change aligns
the two.
The discrepancy happened because jump-register and insert-register
commands use different conventions for translating the prefix argument
to their second function argument: jump-register uses the arg,
insert-register uses (not arg).
=> Match prefix argument handling of insert-register

consult.el
Currently Isearch is still on after finishing `consult-line` when it is invoked from isearch. I've also noticed some key conflicts between isearch and the minibuffer in my setup.
The argument to `isearch-done` makes the current search string not be saved in the isearch history. Feel free to remove it if you think saving is better.
=> consult-line: Quit isearch if applicable

consult.el
This adds previews to `consult-completion-in-region`. The preview code was removed from `consult--yank-read`, put into a little `consult--region-state` function and then used both in `consult--yank-read` and `consult-completion-in-region`.
(I ran into a small snag: `consult--read` cannot be passed a completion table function, because it expects functions to be async collections. I think I have a good workaround for that.)
=> Add previews to consult-completion-in-region

consult.el
This is just a cosmetic improvement, to have shorter paths displayed for recent file candidates in consult buffer. Note that consult-recent-file already abbreviates file names.
=> Abbreviate names of recent files in consult--source-file

consult.el
It doesn't work to show previews for completion in the minibuffer, since we prompt for a completion in a recursive minibuffer obscuring the one where we would be showing the previews.
=> Don't preview completion in region if its in the minibuffer

consult.el
Instead of fontifying the entire buffer, only fontify candidates. This can greatly improve the speed of the first invocation in large buffers. It also allows getting fontification even in buffers larger than consult-fontify-max-size.
Let me know if this is okay. It seems to work well for me in testing. It is instant for me on the first run in files where the previous run took 6 seconds and in files bigger than `consult-fontify-max-size`. I'm not sure there would be a case where there would be enough headings to slow things down as much as `consult-line` in a buffer close to `consult-fontify-max-size` (it seems unlikely), but if there is a limit, I think it should be a separate variable. Let me know what you think.
=> consult-outline: Only fontify candidate lines

consult.el
Here's a sketch for the narrowing by outline level in `consult-outline`.
Some comments:
* I don't like the `consult--ouline-level` function too much. It would be easy enough to compute the level when building the candidate list, but then I would have to change `consult--location-candidate` to allow including this extra datum in each candidate.
* For now, I'm requiring `outline` in the body of `consult--ouline-level`. If we reimplemented code from `outline` to avoid requiring it, it wouldn't add that many lines of code. Still, I don't quite see why not `(require 'outline)` in the body of `consult-outline` itself. Then `consult--outline-candidates` could also be slightly simplified.
* There's nothing forcing outline levels to be contiguous numbers (for instance, the smallest level in …
=> Add narrowing to consult-outline

README.org, consult-org.el, consult.texi
Possible org-related commands were already discussed in the wishlist thread. In my opinion, the two most useful actions would be jumping to an agenda item and clocking in. This pull request is a draft for those two commands.
Possible improvements:
* Flatten the tree structure. That is, insetead of showing candidates
```
* Heading 1
** Subheading 1.1
* Heading 2
```
display this as
```
Heading 1
Heading 1 > Subheading 1.1
Heading 2
```
* Add narrowing. One could go wild here, and I don't even know what all the possibilities are. Some ideas:
* By TODO/DONE state
* By priority
* By outline level ≤ n
* Performance: Building the candidate list could be slow, if one has lots of stuff in their agenda files. In my case it only takes a fraction of a second, but a lag is still noticeable.
* …
=> consult-agenda and consult-clock-in

consult.el
Use menu items instead, which are now supported by which-key.
See https://github.com/justbur/emacs-which-key/pull/308
=> consult-narrow: Remove which-key pseudo keys

consult.el
Every single consult update I see a warning from the compiler about how this docstring is over 80 characters long! :D
=> Reformat consult--preview-function's wide docstring

CHANGELOG.org, README.org, consult-icomplete.el, consult-selectrum.el, consult-vertico.el, consult.el
@bdarcus @oantolin 
This is the generalized version of `simple-crm`. While this crm implementation is not the perfect solution and may still have other subtle issues, I am actually quite happy with it. I think it is a usability improvement in particular in combination with UIs like Vertico  or Selectrum, but it also works well with default completion. The function is a pretty cheap and non-intrusive addition, independent of the completion UI. This is much more maintainable, in contrast to baking some special crm support directly in the completion UI like Vertico.
My problem here is that I could not get this to work with Embark until now. My main concern is not the multi selection target finder, but the ability to allow `completing-read-multiple` commands to be used as Embark actions. …
=> consult-completing-read-multiple

README.org, consult.el
Previously command line configurations were plain strings which should include
the substrings ARG and OPTS. The substrings were replaced by the input argument
and auxillary command line arguments respectively.
The new command line argument configurations must be lists of strings and
expressions, which are evaluated in a lexical context with the variables `arg`
and `opts`.
Updated configurations:
* consult-find-command
* consult-locate-command
* consult-man-command
* consult-git-grep-command
* consult-grep-command
* consult-ripgrep-command
=> Generalize command line arguments

CHANGELOG.org, README.org, consult.el
The input string is transformed before passing it to the backend. Spaces are
replaced by `.*`. Furthermore the input is interpreted as Emacs regular
expression and transformed to a Perl-compatible regular expression (PCRE), by a
handful of basic substitutions. The matching substrings are not obtained anymore
from the backend by looking for ANSI escape sequences. Instead the input regular
expression is used to heuristically apply highlighting.
Advantages:
- No parsing of ANSI escape sequences, which is fragile and inefficient.
- More flexibility, input string can be transformed, e.g., "def consult" -> "def.*consult".
- Highlighting becomes possible for backends which don't return highlights, e.g., find.
Disadvantages:
- Highlighting may be incorrect. In practice this is rare, since most …
=> Transform input of consult-grep and consult-find commands

consult.el
Hello, @minad!
This is a small fix to make `consult--command-split` remove the `--` from the arguments when splitting an input.
```elisp
~ $ (consult--command-split "case -- --hidden --glob *backup")
("case -- " "--hidden" "--glob" "*backup")
```
`*consult-async*`: `--` is included as a string to match, `(?=.*--)`:
```txt
consult--async-process started ("rg" "--line-buffered" "--color=never" "--max-columns=1000" "--path-separator" "/" "--smart-case" "--no-heading" "--line-number" "." "-P" "-e" "^(?=.*case)(?=.*--)" "--hidden" "--glob" "*backup")
```
```elisp
~ $ (consult--command-split "case -- --hidden --glob *backup")
("case" "--hidden" "--glob" "*backup")
```
`*consult-async*`:
```txt
consult--async-process started ("rg" "--line-buffered" "--color=never" "--max-columns=1000" …
```
=> Fix `consult--command-split`

consult.el
Hi,
I am using bookmarks and I have advised `bookmark-get-filename` so that I can expand placeholders in filename property. Unfortunately `consult` is not able to give a preview because it is using `alist-get` instead of `bookmark-get-filename` thus bypassing the advice. Is there any reason to prefer `alist-get` instead of bookmarks accessors?
Thanks,
=> Consult bookmark using `alist-get`

consult-compile.el
This does the trick for me. We might also either enable recursive minibuffers, or just give up if `compilation-find-file` asks for a directory, but with an appropriate error message.
Fixes #301
=> Call compilation-find-file from the correct directory

consult.el
Previously this was done by using initial as the DIR argument of
read-file-name, but that relied on undocumented behavior of that
function. With this change, we explicitly insert the initial text.
This fixes one of the two issues mentioned in minad/consult#461
=> consult-completion-in-region: insert initial text for file completion

consult-selectrum.el, consult.el
Fix warnings from the compiler about docstrings longer than 80 characters.
=> Reformat wide docstring in consult and consult-selectrum

consult.el
This improves the speed of `consult-focus-lines` by:
- Storing line number + line begin & end as text properties on the line candidates to be matched.
- Extracting this information from the text properties in resulting matches.
- Using the matched line data to merge contiguous blocks of lines, substantially reducing the number of overlays needed.  Overlays are not pre-allocated, but instead deleted and re-created on each new input.
To ensure every line has the `'line` text property added, blank lines are collected as `\n`.  I tested this on a file with >250,000 lines (`/usr/share/dict/words`).  The current version does not make it to the prompt after several minutes of waiting.  This is likely due to the pre-allocation of one overlay per line.  This version works reasonably well on such a …
=> Improve focus-lines speed using multi-line overlays

consult.el
* consult.el (consult-preview-key, consult-bookmark-narrow)
(consult--location-candidate, consult--with-preview)
(consult--async-sink, consult--read, consult--prompt): Fix
warnings about wrong usage of unescaped single quotes in
docstrings issued by Emacs 29.
=> Fix warnings about single quotes in docstrings

README.org
If a custom command wraps a `consult` command, `this-command` is equal
to the name of the custom command, even when a `consult-*` command is
called within it. Since Consult uses the value of `this-command` to
determine whether or not to show a preview, we have to add the name of
our custom `consult-*` wrapping command to the `customize-consult`
call that sets the preview key.
=> change(README): update Live Previews section for custom commands

consult.el
* consult.el (consult-highlight-match): Slightly re-write docstring.
=> Fix compiler warning about docstring wider than 80 characters

consult.el
`consult-mode-histories` can be a cons or 3 element list, the last member of which is the name of an index variable to update with the index position of the selected history element on the history list or ring.  Note that the _first_ such matching element is taken.
=> Enable setting an index var from consult-mode-histories

consult.el
I wasn't aware of `cursor-in-echo-area` when I wrote this function, but it's a much less drastic measure than `inhibit-redisplay` (which makes Emacs temporarily unresponsive to the user).
I'm a bit puzzled by the comments explaining the source of flickering. I don't see any flickering in the mode line on my Emacs 29 with pgtk, even if I disable both let-bindings. The only flickering I can see is in the cursor.
(Also, for the record, when you drop support for Emacs 28 you could rely on `minibuffer-lazy-highlight-setup`. But it's not clear it will simplify `consult-isearch-history` too much.)
=> consult-isearch-history: use cursor-in-echo-area

CHANGELOG.org, README.org, consult.el
This adds support for searching over multiple directories or files sets for all of the consult grep commands when a prefix argument is given to the command.  Space-separated shell glob-type expressions may be given to produce the path set sent to the grep command; expansion is done with file-expand-wildcards.   See the CHANGELOG.org for detailed updates.
=> Add consult support for multi-path and wildcard argument handling

consult-org.el
This patch changes `consult-org--headings` to get tags with `org-get-tags` instead of `org-heading-components`.  This means inherited tags will now be shown (assuming `org-use-tag-inheritance` is non-nil).
Things I've checked:
- `org-get-tags` uses an internal org cache and the cache seems to be enabled on all my org buffers,
- I've run `consult-org-agenda` and `consult-org-headings` on a variety of my buffers and they showed inherited tags,
- I've set `org-use-tag-inheritance` to nil and checked that local tags are still shown, but inherited tags are not.
Disclaimer: While I am a software developer, I am definitely not an elisp developer and I had to lookup the docs for every function I've used.  I don't know if there's a better way to do this.
Closes #765
=> consult-org-*: show inherited tags

consult.el
`man -k` is equivalent to `apropos`.  According to the manpage `apropos (1)` defaults to interpret the patterns as extended regular expressions.
POSIXLY_CORRECT
If $POSIXLY_CORRECT is set, even to a null value, the default apropos search will be as an extended
regex (-r).  Nowadays, this is the default behaviour anyway.
=> consult-man: fix regexp type

consult.el
Use `find-file-noselect` for `consult--grep-position`, otherwise we cannot properly save the point before jump.
I've already assigned FSF copyright.
=> Use find-file-no-select in grep-position

consult.el
This PR adds a minibuffer setup hook to `consult--directory-prompt` which sets up the filename syntax table, like in `read-file-name` here: https://github.com/emacs-mirror/emacs/blob/6abea4d98d1d964c68a78cb9b5321071da851654/lisp/minibuffer.el#L3518-L3537
I'm not sure if we would want some of the other setup in the `read-file-name` hook (like setting the `M-n` default to the selected buffer file), but setting the syntax table fixes functions like `backward-kill-sexp` not working right when running for example `consult-grep` with a prefix arg to select the dir to run in (it would kill past `/` delimiters).
=> consult--directory-prompt: Use filename syntax table

CHANGELOG.org, README.org, consult.el
This fixes the problem where buffers are renamed during completion. Renaming can happen during buffer name uniquify or due to EXWM renaming. See the issues #978 and #979.
Consult buffer preview magically continues to work since `get-buffer` accepts both string and buffer arguments. I haven't tested Embark yet.
=> Use (cons 'buffer . buffer-object) as multi-category for candidates

consult-kmacro.el
Without this patch, byte-compile throws an error because `thread-last` is not found. `consult.el` already contains the same form for `require`-ing `subr-x`, but the macro won't be available for `consult-kmacro.el` at compile time, unless it is loaded again like this?
=> consult-kmacro: Silence byte-compiler

consult.el
See https://github.com/minad/vertico/discussions/533 for related discussion.
Ensure that the global completion style settings are used for `consult-line`, `consult-focus-lines` and `consult-keep-lines` filtering. This override is necessary since users may want to override the settings buffer-locally for in-buffer completion, e.g., via Corfu.
cc @jdtsmith
=> consult-line: Enforce global completion style settings

consult.el
Using completion-boundaries here is incorrect and doesn't work in practice for completion tables with non-trivial boundaries.  The correct thing to do is to use the base-size returned as the cdr of the last element of completion-all-completions.
=> Use the base-size returned by completion-all-completions correctly
